import type { RouteConfig } from '@/types/router'

export const basicRoutes: RouteConfig[] = [
  {
    key: 'dashboard',
    name: '仪表盘',
    path: '/dashboard',
    resourcePath: '../pages/Dashboard/index.tsx',
    meta: {
      isRoute: true,
      isMenu: true,
      icon: 'dashboard',
      sort: 0,
      permissionKey: 'dashboard:view',
      accessControlList: [{ code: 'dashboard:view', name: '查看仪表盘', type: 'page' }],
    },
  },
  {
    key: 'system',
    name: '系统管理',
    path: '/system',
    meta: {
      isRoute: false,
      isMenu: true,
      icon: 'setting',
      sort: 50,
    },
    children: [
      {
        key: 'permission-test',
        name: '权限测试',
        path: '/permission-test',
        resourcePath: '../pages/PermissionTest/index.tsx',
        meta: {
          isRoute: true,
          isMenu: true,
          icon: 'safety',
          sort: 998,
          permissionKey: 'system:permission:test',
          accessControlList: [{ code: 'system:permission:test', name: '权限测试', type: 'page' }],
        },
      },
      {
        key: 'breadcrumb-test',
        name: '面包屑测试',
        path: '/breadcrumb-test',
        resourcePath: '../pages/BreadcrumbTest/index.tsx',
        meta: {
          isRoute: true,
          isMenu: true,
          icon: 'compass',
          sort: 997,
          permissionKey: 'system:breadcrumb:test',
          accessControlList: [{ code: 'system:breadcrumb:test', name: '面包屑测试', type: 'page' }],
        },
      },
    ],
  },
  {
    key: 'examples',
    name: '示例页面',
    path: '/examples',
    meta: {
      isRoute: false,
      isMenu: true,
      icon: 'appstore',
      sort: 100,
    },
    children: [
      {
        key: 'table-example',
        name: '表格示例',
        path: '/examples/table',
        resourcePath: '../pages/TableExample/index.tsx',
        meta: {
          isRoute: true,
          isMenu: true,
          icon: 'table',
          sort: 101,
          permissionKey: 'examples:table:view',
          accessControlList: [{ code: 'examples:table:view', name: '查看表格示例', type: 'page' }],
        },
      },
      {
        key: 'form-example',
        name: '表单示例',
        path: '/examples/form',
        resourcePath: '../pages/FormExample/index.tsx',
        meta: {
          isRoute: true,
          isMenu: true,
          icon: 'form',
          sort: 102,
          permissionKey: 'examples:form:view',
          accessControlList: [{ code: 'examples:form:view', name: '查看表单示例', type: 'page' }],
        },
      },
      {
        key: 'charts-example',
        name: '图表示例',
        path: '/examples/charts',
        resourcePath: '../pages/ChartsExample/index.tsx',
        meta: {
          isRoute: true,
          isMenu: true,
          icon: 'bar-chart',
          sort: 103,
          permissionKey: 'examples:charts:view',
          accessControlList: [{ code: 'examples:charts:view', name: '查看图表示例', type: 'page' }],
        },
      },
    ],
  },
  {
    key: 'user-management',
    name: '用户管理',
    path: '/user',
    meta: {
      isRoute: false,
      isMenu: true,
      icon: 'user',
      sort: 200,
    },
    children: [
      {
        key: 'user-list',
        name: '用户列表',
        path: '/user/list',
        resourcePath: '../pages/User/UserList/index.tsx',
        meta: {
          isRoute: true,
          isMenu: true,
          sort: 201,
          permissionKey: 'user:list:view',
          accessControlList: [
            { code: 'user:list:view', name: '查看用户列表', type: 'page' },
            { code: 'user:create', name: '创建用户', type: 'operation' },
            { code: 'user:edit', name: '编辑用户', type: 'operation' },
            { code: 'user:delete', name: '删除用户', type: 'operation' },
          ],
        },
      },
      {
        key: 'role-management',
        name: '角色管理',
        path: '/user/roles',
        resourcePath: '../pages/User/RoleManagement/index.tsx',
        meta: {
          isRoute: true,
          isMenu: true,
          sort: 202,
          permissionKey: 'user:roles:view',
          accessControlList: [
            { code: 'user:roles:view', name: '查看角色列表', type: 'page' },
            { code: 'user:roles:create', name: '创建角色', type: 'operation' },
            { code: 'user:roles:edit', name: '编辑角色', type: 'operation' },
            { code: 'user:roles:delete', name: '删除角色', type: 'operation' },
          ],
        },
      },
    ],
  },
  {
    key: 'statistics',
    name: '数据统计',
    path: '/statistics',
    resourcePath: '../pages/Statistics/index.tsx',
    meta: {
      isRoute: true,
      isMenu: true,
      icon: 'bar-chart',
      sort: 300,
      permissionKey: 'statistics:view',
      accessControlList: [
        { code: 'statistics:view', name: '查看数据统计', type: 'page' },
        { code: 'statistics:export', name: '导出统计数据', type: 'operation' },
      ],
    },
  },
  {
    key: 'personal',
    name: '个人中心',
    path: '/personal',
    meta: {
      isRoute: false,
      isMenu: true,
      icon: 'user',
      sort: 400,
    },
    children: [
      {
        key: 'profile',
        name: '个人信息',
        path: '/personal/profile',
        resourcePath: '../pages/Profile/index.tsx',
        meta: {
          isRoute: true,
          isMenu: true,
          sort: 401,
          permissionKey: 'profile:view',
          accessControlList: [
            { code: 'profile:view', name: '查看个人信息', type: 'page' },
            { code: 'profile:edit', name: '编辑个人信息', type: 'operation' },
          ],
        },
      },
    ],
  },
  {
    key: 'help',
    name: '帮助中心',
    path: '/help',
    resourcePath: '../pages/Help/index.tsx',
    meta: {
      isRoute: true,
      isMenu: true,
      icon: 'question-circle',
      sort: 500,
      permissionKey: 'help:view',
      accessControlList: [{ code: 'help:view', name: '查看帮助中心', type: 'page' }],
    },
  },
  {
    key: 'about',
    name: '关于我们',
    path: '/about',
    resourcePath: '../pages/About/index.tsx',
    meta: {
      isRoute: true,
      isMenu: true,
      icon: 'info-circle',
      sort: 600,
      permissionKey: 'about:view',
      accessControlList: [{ code: 'about:view', name: '查看关于页面', type: 'page' }],
    },
  },
]
